### ISSUE TITLE
Why "optionals" on your model? Why optionals everywhere?

### ISSUE THREAD

**Issue by mendesbarreto** [Viniciuscarvalho/MarvelApp#1]
https://github.com/Viniciuscarvalho/MarvelApp/blob/1dbb7fe9db73e061230bd77af227723c485726ce/MarvelApp/MarvelApp/Shared/Models/Comic.swift#L20

The sooner you treat your optional, sooner you be happy. This will avoid a chain of optionals in the layer of mode transformation and consequently at your view and viewmodels

**Comment by Viniciuscarvalho** [comment]
Would you guard all of the elements? In the API, the elements are optional.
