### ISSUE TITLE
Bye bye "fileprivate"!

### ISSUE THREAD

**Issue by mendesbarreto** [Viniciuscarvalho/MarvelApp#3]
https://github.com/Viniciuscarvalho/MarvelApp/blob/f591ca622e884b5b7fb23ab1eddeede16242e52f/MarvelApp/MarvelApp/Characters/ViewControllers/CharactersViewController.swift#L16

The modifier fileprivate will vanish from next Swift versions:

https://swifting.io/blog/2017/05/30/43-bye-bye-fileprivate/

**Comment by Viniciuscarvalho** [comment]
Amém! 👍
