### ISSUE TITLE
Why your list of search result is optinal? Why you do not use a empty list with 0 elements?

### ISSUE THREAD

**Issue by mendesbarreto** [Viniciuscarvalho/MarvelApp#4]
https://github.com/Viniciuscarvalho/MarvelApp/blob/f591ca622e884b5b7fb23ab1eddeede16242e52f/MarvelApp/MarvelApp/Characters/ViewModel/CharactersViewModel.swift#L26

**Comment by mendesbarreto** [comment]
This issue is correlated with the #1

**Comment by Viniciuscarvalho** [comment]
I have no case for when there are no results to search, should create a screen for empty state, so I'm putting that check guard.

**Comment by mendesbarreto** [comment]
This is exactly what you shouldn't used. 

Avoid nulables on model layer will avoid unnecessary code  complexity. Imagine that every time you get this list to read, you would have to do a conditional "if" == "?". When you choose add a Nuable variable you will force all other classes which use it to make a if .
